baseURL: https://jennifersu.netlify.app/
languageCode: en-us
title: Jennifer's website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner: 
    buttonText: Get Started
#    subtitle: |-
#      A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
#      AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Jennifer
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
#        street: Street
        title: Location
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: jsu.mfa2022@london.edu
        title: Email
    enable: yes
    phone: 
      - phone: +44 (07) 536 215 396
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Jennifer Ziyao Su
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
#     - icon: fa-twitter
#       label: Twitter
#       url: https://www.twitter.com
      - icon: fa-youtube
        label: YouTube
        url: https://www.youtube.com/channel/UCZ_o1dErJQxiOKgEXzQ04pQ
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/_homebistro_/?hl=en
      - icon: fa-github
        label: GitHub
        url: https://www.github.com
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/jenniferziyaosu/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/forest
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: Jen's Website
    title: Home
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: China -> Canada -> United Kingdom
        title: Education
        url: blogs/uoft
      - image: lbs.jpg
        subtitle: Capital Markets -> Private Investments
        title: R Experience
        url: blogs/jennifer
      - image: food.jpg
        subtitle: The HomeBistro Kitchen
        title: Food Adventurer
        url: blogs/homebistro
      - image: travel.jpg
        subtitle: Museum of Memories
        title: Traveller
        url: blogs/zermatt
      - image: music.jpg
        subtitle: Soul of my life
        title: Music 
        url: blogs/piano1
      - image: tennis.jpg
        subtitle: Sweat in the sun
        title: Sports
        url: blogs/tennis
  two:
    buttonText: Watch Again
    enable: yes
    subtitle: ""
    title: Thanks for Visiting
 #   url: blogs
